//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LULU_WCF_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtttendedClass
    {
        public int AttendedClassID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
        public virtual GPS_Login GPS_Login { get; set; }
        public virtual Staff_Login Staff_Login { get; set; }
    }
}
