//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LULU_WCF_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer : Staff_User
    {
        public string Title { get; set; }
    }
}
