//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LULU_WCF_Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LULU_ModelContainer : DbContext
    {
        public LULU_ModelContainer()
            : base("name=LULU_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<AtttendedClass> AtttendedClasses { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Course> Courses1 { get; set; }
        public virtual DbSet<ClassRoom> ClassRooms1 { get; set; }
        public virtual DbSet<Campus> Campus { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
